name: Build Linux
on:
  workflow_dispatch:
  push:
    paths:
      - "**.yml"
      - "**.sh"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
      with:
        fetch-depth: 1
    - name: Build deps
      run: |
        ./setup/packages.debian.sh
        ./setup/source.kernel.org.sh
    - name: ccache
      uses: actions/cache@main
      with:
        path: ${{ github.workspace }}/linux/out/.ccache
        key: ccache-${{ github.run_id }}
        restore-keys: ccache-
    - name: Run build
      run: |
        echo "USE_CCACHE=1; DEFCONFIG=tinyconfig;" > Build.options
        cd linux
        ccache -o cache_dir="$(pwd)/out/.ccache"
        ccache -o compression=false
        ../build.sh -j2
