name: Build Linux
on:
- workflow_dispatch
- push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 1
    - name: Build deps
      run: |
        ./setup/debian.sh
        git clone https://github.com/torvalds/linux.git --depth=1 --no-tags
    - name: ccache
      uses: actions/cache@v6
      with:
        path: ${{ github.workspace }}/linux/out/.ccache
        key: ccache-${{ github.run_id }}
        restore-keys: ccache-
    # - name: ThinLTO cache
    #   uses: actions/cache@v6
    #   with:
    #     path: ${{ github.workspace }}/out/.thinlto-cache
    #     key: thinlto-${{ github.run_id }}
    #     restore-keys: thinlto-
    - name: Run build
      run: |
        echo "USE_CCACHE=1; DEFCONFIG=tinyconfig;" > Build.options
        cd linux
        ccache -o cache_dir="$(pwd)/out/.ccache"
        ccache -o compression=false
        ../build.sh -j2
